### PR TITLE
Update to constitution

### PR DESCRIPTION
**Pull request by Floppy**
I hereby call a meeting of the Executive Board of Something New, currently consisting of:
- Raymond James Smith (@floppy)
- Paul Robinson (@pauljrobinson)
- Philip John (@philipjohn)
- Andrew Williams (@andrewdwilliams)

Only item on the agenda is the amendment of the constitution, as proposed in this pull request. This meeting will be carried out _in the comments of this pull request_, and this pull request will form the official minutes of the meeting. 
# Item 1: Constitution

I've proposed some changes to the constitution. The main points are:
- To open membership to anyone, not just UK citizens. Voting rights are restricted to UK registered voters. This will allow us to build international links through membership.
- To explicitly allow online votes for board meetings and constitutional changes.
- Make the Nominating Officer and Party Treasurer positions directly elected by the membership.
- Remove powers of direct appointment from the Party Leader and give them to the membership or Executive Board.
- Make sure that nominations for officer posts are opened before each biennial general meeting. This means that officers have to be explicitly voted in every time; no jobs for life here!

Please discuss the new wording, and vote on whether to accept. Vote yes with 👍 and vote no with 👎.

When agreed, the new constitution will be submitted to the Electoral Commission.

### CODE REVIEW

**Comment by PaulJRobinson** [comment]
My only concern is the membership being open to anyone and removing the requirement to be a UK resident. I don't see the reasoning on this. It could in theory lead to a takeover by (eg) pro Putin Russian residents who then control a UK party behind the scenes. But what does it gain us?

All the other points I'm happy with.

**Comment by PaulJRobinson** [comment]
I'm usually pretty relaxed on commits where I hold a wavering view, but on that point alone I'm currently a :-1:

**Comment by Floppy** [comment]
And that's absolutely the correct approach in this case, thankyou :)

The thinking behind international membership (and this could be completely wrong, I'm unsure of it myself) was that (a) it's hard to enforce UK only membership anyway, (b) this is as yet a small movement, so some international members might help in building momentum, and (c) we're an internationalist party, so international perspectives might be useful. Having said that, as everything is open anyway, there's nothing to stop people from outside the UK taking part in manifesto creation and discussion without being proper members.

The constitution as amended allows international members, but does not allow them voting or standing rights, which was my attempt to stop a hostile foreign takeover.  But maybe as we're a UK organisation by definition, it doesn't make sense.

**Comment by PaulJRobinson** [comment]
What about affiliate membership for non UK residents?  

## 

Paul Robinson

**Comment by Floppy** [comment]
Yes, we could perhaps make it a separate type in the constitution and work it out with filters in the member database itself.

**Comment by anilliams** [comment]
Of course, I would imagine we would, to an extent, vet potential members, and reserve the right to revoke/deny membership. This would surely go some way in preventing any Russian takeover of Something New, the prized target that we are.

**Comment by Floppy** [comment]
We'd need something in the constitution about that, I guess; how we could revoke membership?

**Comment by philipjohn** [comment]
I knew those Russians were up to something 😉

My feeling on that point is that as an internationalist party we're going to want to build alliances with other parties. One way we might do so is to share memberships, whereby members can join SN, and we can join theirs.

The rules on voting rights don't give non-UK residents the ability to actually do anything so the only "takeover" threat in reality would come from UK residents.

I'm a :+1: on this lot.

**Comment by philipjohn** [comment]
Also: I'm in love with the fact we can build a party like this!

**Comment by Floppy** [comment]
@PaulJRobinson any further thoughts, or should I propose a change for a more explicit "international membership" category that doesn't have any rights? The effect would be the same, but perhaps more explicit.

**Comment by anilliams** [comment]
I'm fine with non-UK members as long as they are sufficiently restricted to prevent a worst case scenario. If it's easier to discern UK and non-UK members if they are in two distinct categories, then I would also support that. So, yes, @Floppy, I agree that we could certainly implement a new 'international membership' category, making it more explicit.

The rest of the constitution looks fine to me - no one else has picked up on any areas of concern, so I think we're heading towards a green light. From a scan of the text, there are a few things we need to organise post-constitution:
- How a BGM will work, and when/where to have our first one
- Rules on how to submit motions for debate at the BGM (Found an issue: 5.5 doesn't really serve a purpose after the new 5.3 has been put in.)
- Rules for the selection of candidates and conduct of meetngs
- Rules for election to the Executive Board
- Rules on the creation of local party branches
- Just a pointer - the election system for leader is 'transferable ballot'. Personally I would recommend STV for all internal elections unless it is not practicable, but this does not need to be put in the constitution.
- Who will operate as returning officer for future internal elections? Should this be a party officer position for us to add in the future?

**Comment by anilliams** [comment]
@floppy Thoughts on my post above?

**Comment by Floppy** [comment]
Sorry, meant to reply. That all makes sense, and we can write some extra guidance to cover the parts you mention. I've got it on my list to clean up the international membership stuff based on the feedback here, so that's currently on me. Will try to get it done this weekend and we can move on.

**Comment by Floppy** [comment]
OK, @PaulJRobinson @philipjohn @andrewdwilliams, I've made some changes around membership. International membership is now explicitly a separate category, and is stated to not be included in mentions of "membership" unless explicitly stated. That should cover it.

Agree @andrewdwilliams we'll want to write some official rules around candidate selection, and internal elections, as a separate thing.

**Comment by PaulJRobinson** [comment]
:+1:

## 

Paul Robinson

**Comment by Floppy** [comment]
Annual renewal of registration is coming up, and I can submit an updated constitution with it, so it would be good to get this closed off. Votes, @andrewdwilliams and @philipjohn?

**Comment by anilliams** [comment]
:+1:

**Review by philipjohn — APPROVED** [review]

**Comment by philipjohn** [comment]
:+1: Sorry for being so slow folks.

**Comment by Floppy** [comment]
And with that, the change is approved and the meeting adjourned. Thankyou everyone! :)

**Pull request merged**
